### ISSUE TITLE
transition to openapi-generator not quite working

### ISSUE THREAD

**Issue by RLogik** [RLogik/phpytex#7]
I have started to integrate usage of openapi-generator (v4.3.1, OAS3 standard) to generate the models. To run the generator I am using `openapi-generator-cli` with the **python-experimental** option. That seems to do the trick (compared with the **python** option). An issue remains that it is unclear how to actually _use_ the generated classes. E. g. if the class is defined in a yml file as

```
components:
  schemes:
    max-lines:
      type: integer
      minimumValue: 100
      maximumValue: 100000
```

then the generated class is something like `MaxLines`. It is (currently) unclear to me how to _use_ this in the following senses:

- casting a raw value (e. g. a python `str` or `int` type) to a `MaxLines`-type
- checking whether a raw value can be casted to the `MaxLines` type.
